name: released image to SWR
on:
  release:
    types:
      - published
jobs:
  release-image:
    name: release images
    # prevent job running from forked repository, otherwise
    # 1. running on the forked repository would fail as missing necessary secret.
    # 2. running on the forked repository would use unnecessary GitHub Action time.
    if: ${{ github.repository == 'kubernetes-sigs/cloud-provider-huaweicloud' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
        with:
          driver: docker-container
      - name: Build and push images
        env:
          REGISTRY: ${{secrets.SWR_REGISTRY}}
          REGISTRY_USERNAME: ${{secrets.SWR_REGISTRY_USER_NAME}}
          REGISTRY_PASSWORD: ${{secrets.SWR_REGISTRY_PASSWORD}}
          REGISTRY_SERVER_ADDRESS: ${{secrets.SWR_REGISTRY_SERVER_ADDRESS}}
          VERSION: ${{ github.ref_name }}
        run: make release
